services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    platform: 'linux/amd64'
    image: mysql:8.0.39
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: discussr_hello
      MYSQL_USER: discussr_user
      MYSQL_PASSWORD: password
      # MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # MYSQL_DATABASE: $MYSQL_DATABASE
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_PASSWORD

    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
