    name: Deploy MultiDocker
    on:
      push:
        branches:
          - master # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t kolyad3v/discussr .
          - run: docker push kolyad3v/discussr
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'

          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: discussr
              environment_name: Discussr-env
              existing_bucket_name: elasticbeanstalk-us-east-1-152921919484
              region: us-east-1
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip